CREATE DATABASE IF NOT EXISTS cs208demo;

USE cs208demo;

CREATE TABLE IF NOT EXISTS reviews (
    id INT AUTO_INCREMENT PRIMARY KEY,
    comment VARCHAR(360) NOT NULL
);

INSERT INTO reviews (comment)
VALUES ('test comment');